resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/00487726c4bc21b4744e59d913334ebfeac7d68e/snapshot.yaml

packages:
  - .

extra-deps:

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: dd30455144e11efb435619383ba84ce02aee720d
    subdirs:
      - iohk-monitoring
      - contra-tracer
      - plugins/backend-ekg
      - tracer-transformers

  - git: https://github.com/input-output-hk/cardano-base
    commit: eed4fc484366214831576eef0c7fe90d1d08c78b
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: c62e2eeba5756898cbf59732fccd6a83a4065c18
    subdirs:
      - cardano-ledger/test
      - cardano-ledger
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: f27e8b66a393f0b7da1893889dcea07da0fe4dec
    subdirs:
      # small-steps
      - byron/semantics/executable-spec
      # cs-ledger
      - byron/ledger/executable-spec
      # cs-blockchain
      - byron/chain/executable-spec

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 00487726c4bc21b4744e59d913334ebfeac7d68e
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: bc3563c952d9f3635e1c76749b86b0a24f7e4b83
    subdirs:
      - cardano-shell

    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 398004e1403367cc2a25c639eb6349d473e51b2d
    subdirs:
      - ouroboros-consensus
      - ouroboros-network
      - io-sim-classes
      - io-sim
      - network-mux
      - typed-protocols
      - typed-protocols-cbor

  - bimap-0.4.0
  - binary-0.8.7.0
  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3@sha256:cde383c356bc41136ed53cd27e0800f46dbd2185600dd0de18d66d5c49739d94
  - libsystemd-journal-1.4.4
  - prometheus-2.1.2
  - quickcheck-state-machine-0.6.0@sha256:3e4f8df0f6b5d415e3c8840dc75034a63e37f56f5f8cfa1035ded16345235ac4
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.1
  - time-units-1.0.0
  - katip-0.8.3.0
  - statistics-linreg-0.3

  # Windows only
  - Win32-2.5.4.1

  # The parts of cardano-sl that are needed for the byron proxy.
  - git: https://github.com/input-output-hk/cardano-sl
    commit: ff10fcb2c6706175df57bb8b9c8008231a8fbe18
    subdirs:
      - lib
      - binary
      - binary/test
      - util
      - util/test
      - infra
      - infra/test
      - core
      - core/test
      - chain
      - chain/test
      - db
      - db/test
      - crypto
      - crypto/test
      - networking

  - git: https://github.com/input-output-hk/log-warper
    commit: 16246d4fbf16da7984f2a4b6c42f2ed5098182e4

  - git: https://github.com/input-output-hk/rocksdb-haskell-ng
    commit: 49f501a082d745f3b880677220a29cafaa181452

  - git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c

  - git: https://github.com/avieth/network-transport-tcp
    commit: 2024d562d693518d983943331838b1857c2bf063

  - git: https://github.com/input-output-hk/universum
    commit: 15f7db758ff5a24b874de2247f6f7a4576562da5

  - git: https://github.com/input-output-hk/serokell-util
    commit: 457f1d149c6e238841f283a1faf7bc8fb021b27d

  - git: https://github.com/input-output-hk/ether
    commit: a311878ae17ed5f201421bdcd5392a24b746ff0b

  - git: https://github.com/input-output-hk/transformers-lift
    commit: c830bc7e7e41895e3c50488a92d34405b68b4ad8

  - aeson-options-0.1.0
  - pvss-0.2.0
  - lrucache-1.2.0.1
  - writer-cps-mtl-0.1.1.6
  - writer-cps-transformers-0.5.6.0
  - o-clock-1.0.0.1
  - ekg-wai-0.1.0.3
  - lzma-clib-5.2.2

  - network-3.1.0.1
  - systemd-2.0.0
  - socks-0.6.0
  - connection-0.3.0
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - snap-core-1.0.4.0-r2
  - snap-server-1.1.1.1
  - swagger2-2.4
  # Needed by swagger2 version (InsOrd module)
  - insert-ordered-containers-0.2.2
  # Neede because of swagger2
  - servant-swagger-1.1.7.1
  # Needed because of servant-swagger
  - servant-0.16.1
  - servant-client-0.16
  - servant-client-core-0.16
  - servant-server-0.16.1
  - servant-blaze-0.9
  - http-api-data-0.4.1
  - time-compat-1.9.2.2

  - Unique-0.4.7.6
  - moo-1.2
  - gray-code-0.3.1

ghc-options:
  cardano-byron-proxy:     -Wall -Werror -Wcompat -fwarn-redundant-constraints -fwarn-incomplete-patterns -fwarn-unused-imports -Wincomplete-record-updates -Wincomplete-uni-patterns

nix:
  shell-file: nix/stack-shell.nix
