resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3c40edcf5bdba8721d3430d0aaaeea8770ce9bec/snapshot.yaml

packages:
  - .

extra-deps:

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 4956b32f039579a0e7e4fd10793f65b4c77d9044
    subdirs:
      - iohk-monitoring
      - contra-tracer
      - plugins/backend-ekg

  - git: https://github.com/input-output-hk/cardano-base
    commit: 057d8a9a3e751f88fc7677df5713c5ecc47a37c4
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: dbdb643722e431e4d232345a0eafdc7bdeab7b60
    subdirs:
      - cardano-ledger
      - crypto

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3c40edcf5bdba8721d3430d0aaaeea8770ce9bec
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 4d26bcefc0edcd99154c85170ef028775c6dd1e0
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 0476dce67251a324432f3351e726646ac583597a
    subdirs:
      - ouroboros-consensus
      - ouroboros-network
      - io-sim-classes
      - network-mux
      - typed-protocols
      - typed-protocols-cbor

  - bimap-0.4.0
  - binary-0.8.7.0
  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3@sha256:cde383c356bc41136ed53cd27e0800f46dbd2185600dd0de18d66d5c49739d94
  - libsystemd-journal-1.4.4
  - prometheus-2.1.2
  - quickcheck-state-machine-0.6.0@sha256:3e4f8df0f6b5d415e3c8840dc75034a63e37f56f5f8cfa1035ded16345235ac4
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.1
  - time-units-1.0.0
  - katip-0.8.3.0
  - statistics-linreg-0.3

  # Windows only
  - Win32-2.5.4.1

  # The parts of cardano-sl that are needed for the byron proxy.
  - git: https://github.com/input-output-hk/cardano-sl
    commit: d0cc2e6336e3c57771c775cafe831bc83db303d3
    subdirs:
      - lib
      - binary
      - binary/test
      - util
      - util/test
      - infra
      - infra/test
      - core
      - core/test
      - chain
      - chain/test
      - db
      - db/test
      - crypto
      - crypto/test
      - networking

  - git: https://github.com/input-output-hk/log-warper
    commit: 16246d4fbf16da7984f2a4b6c42f2ed5098182e4

  - git: https://github.com/input-output-hk/rocksdb-haskell-ng
    commit: 49f501a082d745f3b880677220a29cafaa181452

  - git: https://github.com/avieth/kademlia
    commit: 38a0575bb303804461f4b6176ca38eba81adbd79

  - git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c

  - git: https://github.com/avieth/network-transport-tcp
    commit: 46f2942423d9ad3c81040565a9e9d5b9e08ddcc4

  - git: https://github.com/input-output-hk/universum
    commit: 15f7db758ff5a24b874de2247f6f7a4576562da5

  - git: https://github.com/input-output-hk/serokell-util
    commit: 457f1d149c6e238841f283a1faf7bc8fb021b27d

  - git: https://github.com/input-output-hk/ether
    commit: a311878ae17ed5f201421bdcd5392a24b746ff0b

  - git: https://github.com/input-output-hk/transformers-lift
    commit: c830bc7e7e41895e3c50488a92d34405b68b4ad8

  - aeson-options-0.1.0
  - pvss-0.2.0
  - lrucache-1.2.0.1
  - writer-cps-mtl-0.1.1.6
  - writer-cps-transformers-0.5.6.0
  - o-clock-1.0.0.1
  - ekg-wai-0.1.0.3
  - lzma-clib-5.2.2

ghc-options:
  cardano-byron-proxy:     -Wall -Werror -Wcompat -fwarn-redundant-constraints -fwarn-incomplete-patterns -fwarn-unused-imports -Wincomplete-record-updates -Wincomplete-uni-patterns

nix:
  shell-file: nix/stack-shell.nix
